baseURL: https://nicolasprothero.github.io/NicolasProthero-ArtBlog/
languageCode: en-us
title: Nic Prothero's Blog
theme: PaperMod
enableEmoji: true
publishDir: 'docs'

params:
    homeInfoParams:
        Title: Hi there {{< emoji ":wave:" >}}
        Content: Welcome to Nicolas Prothero's blog for DIG2131C.

    socialIcons: # optional
        - name: "instagram"
          url: "https://instagram.com/nic_hase"