baseURL: https://nicolasprothero.github.io/NicP-Blog/
languageCode: en-us
title: Nicolas Prothero's Blog
theme: PaperMod
enableEmoji: true
publishDir: 'docs'

params:
    homeInfoParams:
        Title: Hi there {{< emoji ":wave:" >}}
        Content: Can be Info, links, about...

    socialIcons: # optional
        - name: "instagram"
          url: "https://instagram.com/nic_hase"
        - name: "github"
          url: "https://github.com/nicolasprothero"